import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: '모두다블럭',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1', // 뷰포트 설정 추가
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#FFF8EC] custom-cursor">
      <head>
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2998824044846392"
          crossOrigin="anonymous"
        ></script>
      </head>
      <body>{children}</body>
    </html>
  );
}
