import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: '다양한 퀴즈 게임',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="max-w-[1024px] mx-auto">
      <head>
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2998824044846392"
          crossOrigin="anonymous"
        ></script>
      </head>
      <body className=" px-4 py-2">{children}</body>
    </html>
  );
}
