export const proverbList = [
  { question: '콩 심은데 콩나고', answer: '팥 심은데 팥 난다' },
  { question: '가는 말이 고와야', answer: '오는 말이 곱다' },
  { question: '백지장도', answer: '맞들면 낫다' },
  { question: '등잔 밑이', answer: '어둡다' },
  { question: '호랑이도', answer: '제 말 하면 온다' },
  { question: '원숭이도', answer: '나무에서 떨어진다' },
  { question: '뛰는 놈 위에', answer: '나는 놈 있다' },
  { question: '고생 끝에', answer: '낙이 온다' },
  { question: '길고 짧은 것은', answer: '대봐야 안다' },
  { question: '티끌 모아', answer: '태산' },
  { question: '바늘 도둑이', answer: '소 도둑 된다' },
  { question: '병 주고', answer: '약 준다' },
  { question: '소 잃고', answer: '외양간 고친다' },
  { question: '가랑비에', answer: '옷 젖는 줄 모른다' },
  { question: '윗물이 맑아야', answer: '아랫물이 맑다' },
  { question: '하룻강아지', answer: '범 무서운 줄 모른다' },
  { question: '꿩 대신', answer: '닭' },
  { question: '쇠귀에', answer: '경 읽기' },
  { question: '바람 앞의', answer: '등불' },
  { question: '낫 놓고', answer: '기역자도 모른다' },
  { question: '아닌 밤중에', answer: '홍두깨' },
  { question: '우물 안', answer: '개구리' },
  { question: '돌다리도', answer: '두들겨 보고 건너라' },
  { question: '가는 날이', answer: '장날이다' },
  { question: '닭 쫓던 개', answer: '지붕 쳐다본다' },
  { question: '말 한 마디에', answer: '천 냥 빚 갚는다' },
  { question: '궁하면', answer: '통한다' },
  { question: '열 길 물 속은 알아도', answer: '한 길 사람 속은 모른다' },
  { question: '쇠뿔도', answer: '단김에 빼라' },
  { question: '뱁새가 황새 따라가면', answer: '가랑이가 찢어진다' },
  { question: '세 살 버릇', answer: '여든까지 간다' },
  { question: '개천에서', answer: '용 난다' },
  { question: '모로 가도', answer: '서울만 가면 된다' },
  { question: '개구리', answer: '올챙이 적 생각 못한다' },
  { question: '걷기도 전에', answer: '뛰려 한다' },
  { question: '제 눈에', answer: '안경이다' },
  { question: '가는 떡이 커야', answer: '오는 떡이 크다' },
  { question: '구슬이 서 말이라도', answer: '꿰어야 보배다' },
  { question: '모난 돌이', answer: '정 맞는다' },
  { question: '하늘이 무너져도', answer: '솟아날 구멍이 있다' },
  { question: '믿는 도끼에', answer: '발등 찍힌다' },
  { question: '구더기 무서워', answer: '장 못 담그랴' },
  { question: '물이 깊어야', answer: '고기가 모인다' },
  { question: '아는 길도', answer: '물어 가라' },
  { question: '달리는 말에', answer: '채찍질' },
  { question: '떡 본 김에', answer: '제사 지낸다' },
  { question: '수박', answer: '겉 핥기' },
  { question: '산 넘어', answer: '산이다' },
  { question: '새 발의', answer: '피' },
  { question: '잘 되면 내 덕', answer: '못 되면 조상 탓' },
  { question: '작은 고추가', answer: '맵다' },
  { question: '낮말은 새가 듣고', answer: '밤말은 쥐가 듣는다' },
  { question: '번갯불에', answer: '콩 볶아 먹는다' },
  { question: '배보다', answer: '배꼽이 크다' },
  { question: '호랑이 굴에 들어가도', answer: '정신만 차리면 산다' },
  { question: '천 리 길도', answer: '한 걸음부터' },
  { question: '하늘이 무너져도', answer: '솟아날 구멍이 있다' },
  { question: '비 온 뒤에', answer: '땅이 굳는다' },
  { question: '독 안에 든', answer: '쥐' },
  { question: '사촌이 땅을 사면', answer: '배가 아프다' },
  { question: '누워서', answer: '떡 먹기' },
  { question: '비 온 뒤에', answer: '땅이 굳어진다' },
  { question: '좋은 약은', answer: '입에 쓰다' },
  { question: '늦게 배운 도둑질이', answer: '날 새는 줄 모른다' },
  { question: '웃는 낯에', answer: '침 못 뱉는다' },
  { question: '자라 보고 놀란 가슴', answer: '솥뚜껑 보고 놀란다' },
  { question: '공든 탑이', answer: '무너지랴' },
  { question: '달면 삼키고', answer: '쓰면 뱉는다' },
  { question: '고양이한테', answer: '생선을 맡긴다' },
  { question: '돼지 목에', answer: '진주목걸이' },
  { question: '미운 놈', answer: '떡 하나 더 준다' },
  { question: '한 번 엎지른 물은', answer: '주워 담을 수 없다' },
  { question: '서울에서', answer: '김 서방 찾기' },
  { question: '고양이 목에', answer: '방울 달기' },
  { question: '우물에서', answer: '숭늉 찾는다' },
  { question: '낫 놓고', answer: '기역자도 모른다' },
  { question: '형만 한', answer: '아우 없다' },
  { question: '땅 짚고', answer: '헤엄치기' },
  { question: '돌다리도', answer: '두들겨 보고 건너라' },
  { question: '사공이 많으면', answer: '배가 산으로 간다' },
  { question: '등잔 밑이', answer: '어둡다' },
  { question: '똥이 무서워서 피하냐', answer: '더러워서 피하지' },
  { question: '똥 묻은 개가', answer: '겨 묻은 개 나무한다' },
  { question: '눈 가리고', answer: '아웅한다' },
];

export const idiomList = [
  { question: '고진', answer: '감래' },
  { question: '구사', answer: '일생' },
  { question: '금상', answer: '첨화' },
  { question: '기고', answer: '만장' },
  { question: '동문', answer: '서답' },
  { question: '백전', answer: '백승' },
  { question: '사면', answer: '초가' },
  { question: '불로', answer: '장생' },
  { question: '어불', answer: '성설' },
  { question: '일석', answer: '이조' },
  { question: '천고', answer: '마비' },
  { question: '화룡', answer: '점정' },
  { question: '노심', answer: '초사' },
  { question: '마이', answer: '동풍' },
  { question: '동상', answer: '이몽' },
  { question: '오합', answer: '지졸' },
  { question: '유유', answer: '상종' },
  { question: '설상', answer: '가상' },
  { question: '가화', answer: '만사' },
  { question: '진퇴', answer: '양난' },
  { question: '일취', answer: '월장' },
  { question: '청천', answer: '벽력' },
  { question: '동분', answer: '서주' },
  { question: '인과', answer: '응보' },
  { question: '호가', answer: '호위' },
  { question: '외강', answer: '내유' },
  { question: '횡설', answer: '수설' },
  { question: '조삼', answer: '모사' },
  { question: '풍전', answer: '등화' },
  { question: '동고', answer: '동락' },
  { question: '박장', answer: '대소' },
  { question: '수수', answer: '방관' },
  { question: '역지', answer: '사지' },
  { question: '유비', answer: '무환' },
  { question: '화기', answer: '애애' },
  { question: '일편', answer: '단심' },
  { question: '백발', answer: '백중' },
  { question: '자수', answer: '성가' },
  { question: '일거', answer: '양득' },
  { question: '적반', answer: '하장' },
  { question: '파죽', answer: '지세' },
  { question: '오리', answer: '무중' },
  { question: '애지', answer: '중지' },
  { question: '어부', answer: '지리' },
  { question: '군계', answer: '일학' },
  { question: '동족', answer: '방뇨' },
  { question: '백년', answer: '가약' },
  { question: '일희', answer: '일비' },
  { question: '일사', answer: '천리' },
  { question: '천하', answer: '태평' },
  { question: '혼비', answer: '백산' },
  { question: '유유', answer: '자적' },
  { question: '과유', answer: '불급' },
  { question: '사필', answer: '귀정' },
  { question: '자포', answer: '자기' },
  { question: '감언', answer: '이설' },
  { question: '비일', answer: '비재' },
  { question: '호연', answer: '지기' },
  { question: '권모', answer: '술수' },
  { question: '점입', answer: '가경' },
  { question: '등하', answer: '불명' },
  { question: '고장', answer: '난명' },
  { question: '온고', answer: '지신' },
  { question: '이심', answer: '전심' },
  { question: '만사', answer: '형통' },
  { question: '권선', answer: '징악' },
  { question: '자승', answer: '자박' },
  { question: '일망', answer: '타진' },
  { question: '각골', answer: '난망' },
  { question: '고집', answer: '불통' },
  { question: '독불', answer: '장군' },
  { question: '부전', answer: '자전' },
  { question: '후안', answer: '무치' },
  { question: '후회', answer: '막급' },
  { question: '안하', answer: '무인' },
  { question: '휘황', answer: '찬란' },
  { question: '흥망', answer: '성쇠' },
  { question: '요지', answer: '부동' },
  { question: '우여', answer: '곡절' },
  { question: '우왕', answer: '좌왕' },
  { question: '우유', answer: '부단' },
  { question: '운칠', answer: '기삼' },
  { question: '독수', answer: '공방' },
  { question: '감지', answer: '덕지' },
  { question: '결자', answer: '해지' },
  { question: '명불', answer: '허전' },
  { question: '무용', answer: '지물' },
  { question: '박학', answer: '다식' },
  { question: '반신', answer: '반의' },
  { question: '주야', answer: '장천' },
  { question: '방방', answer: '곡곡' },
  { question: '영웅', answer: '호색' },
  { question: '오밀', answer: '조밀' },
  { question: '좌충', answer: '우돌' },
  { question: '오매', answer: '불망' },
  { question: '전지', answer: '전능' },
  { question: '일목', answer: '요연' },
  { question: '조강', answer: '지처' },
  { question: '죽마', answer: '고우' },
  { question: '양대', answer: '산맥' },
];

export const dailyWordList = [
  { question: '와이', answer: '파이' },
  { question: '카드', answer: '지갑' },
  { question: '손목', answer: '시계' },
  { question: '운전', answer: '면허' },
  { question: '교통', answer: '카드' },
  { question: '휴대', answer: '전화' },
  { question: '지하', answer: '철역' },
  { question: '선글', answer: '라스' },
  { question: '전기', answer: '밥솥' },
  { question: '냉장', answer: '고기' },
  { question: '신용', answer: '카드' },
  { question: '전자', answer: '사전' },
  { question: '다이', answer: '어리' },
  { question: '커피', answer: '머신' },
  { question: '전기', answer: '포트' },
  { question: '운동', answer: '기구' },
  { question: '라면', answer: '사리' },
  { question: '비닐', answer: '봉지' },
  { question: '신문', answer: '기사' },
  { question: '이불', answer: '커버' },
  { question: '우편', answer: '번호' },
  { question: '모자', answer: '걸이' },
  { question: '책상', answer: '서랍' },
  { question: '열쇠', answer: '고리' },
  { question: '바디', answer: '워시' },
  { question: '마스', answer: '크팩' },
  { question: '쿠션', answer: '커버' },
  { question: '종이', answer: '접기' },
  { question: '안경', answer: '닦이' },
  { question: '손톱', answer: '깎이' },
  { question: '우산', answer: '꽂이' },
  { question: '보드', answer: '게임' },
  { question: '모니', answer: '터암' },
  { question: '고무', answer: '장갑' },
  { question: '베개', answer: '커버' },
  { question: '캠핑', answer: '의자' },
  { question: '전기', answer: '장판' },
  { question: '유리', answer: '창문' },
  { question: '전기', answer: '포트' },
  { question: '물병', answer: '자리' },
  { question: '커피', answer: '머신' },
  { question: '타임', answer: '캡슐' },
  { question: '배드', answer: '민턴' },
  { question: '삼각', answer: '지대' },
  { question: '카테', answer: '고리' },
  { question: '푸트', answer: '코트' },
  { question: '쟁반', answer: '짜장' },
  { question: '스핑', answer: '크스' },
  { question: '차돌', answer: '박이' },
  { question: '해리', answer: '포터' },
  { question: '청양', answer: '고추' },
  { question: '만리', answer: '장성' },
  { question: '장원', answer: '급제' },
  { question: '미세', answer: '먼지' },
  { question: '카페', answer: '라떼' },
  { question: '술래', answer: '잡기' },
  { question: '현상', answer: '수배' },
  { question: '재롱', answer: '잔치' },
  { question: '블랙', answer: '핑크' },
  { question: '호루', answer: '라기' },
  { question: '곱창', answer: '전골' },
  { question: '승부', answer: '차기' },
  { question: '헬리', answer: '콥터' },
  { question: '치어', answer: '리더' },
  { question: '계좌', answer: '이체' },
  { question: '탄수', answer: '화물' },
  { question: '크레', answer: '파스' },
  { question: '비타', answer: '오백' },
  { question: '스포', answer: '일러' },
  { question: '만루', answer: '홈런' },
  { question: '스파', answer: '이크' },
];
